---
i18n:
  name: "Configure system to use bootc containers..."

dontChroot: true
timeout: 1800

script:
  - "bootc install to-filesystem --target-transport containers-storage --karg=quiet --karg=splash ${ROOT}"
  - "bootc switch --mutate-in-place --enforce-container-sigpolicy --transport registry tharsis:latest"
