FROM debian:trixie

RUN apt update && DEBIAN_FRONTEND=noninteractive apt install -y jq yq curl wget make build-essential fuse-overlayfs podman skopeo qemu-kvm 

RUN	mkdir -p \
	/app \
	/etc/containers \
	/usr/local/bin \
	/var/lib/flatpak

RUN wget -q https://github.com/sigstore/cosign/releases/download/v3.1.2/cosign_3.1.2_amd64.deb && \
	dpkg -i cosign_3.1.2_amd64.deb

RUN apt install -y \
	debootstrap rsync isolinux syslinux-efi grub-pc-bin grub-efi-amd64-bin grub-efi-ia32-bin \
	xorriso squashfs-tools-ng erofs-utils mtools dosfstools

RUN apt install -y \
	strace tcpdump nmap

WORKDIR /app

COPY --chmod=755 scripts/mklive.sh /usr/local/bin/mklive

CMD ["/usr/local/bin/mklive"]

# VERSION: 1.0.0